"""add unique constraint to userlikes

Revision ID: 57105b1b862c
Revises: 46cbb115e1de
Create Date: 2018-03-23 15:01:27.402515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57105b1b862c'
down_revision = '46cbb115e1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_likes', ['user_id', 'message_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_likes', type_='unique')
    # ### end Alembic commands ###
